name: Build

on:
  workflow_dispatch:
    inputs:
      Alpha:
        description: 'Alpha'
        required: true
        default: 'true'
      Premium:
        description: 'Premium'
        required: true
        default: 'false'
      Foss:
        description: 'Foss'
        required: true
        default: 'false'

jobs:
  build:
    name: "Build APKs"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup gradlew
        run: chmod +x gradlew

      - name: Check build-logic
        run: ./gradlew check -p build-logic

      - name: Decode store file
        run: |
          echo ${{ secrets.ENCODED_STRING }} | base64 -di > "./app/${{ secrets.STORE_FILE }}"

      - name: Build with gradle
        id: gradle
        run: |
          TASKS=""
          if [ "${{ github.event.inputs.Alpha }}" = 'true' ]; then
            TASKS="$TASKS assembleArm64-v8aAlphaRelease assembleArmeabi-v7aAlphaRelease assembleX86AlphaRelease assembleX86_64AlphaRelease"
          fi
          if [ "${{ github.event.inputs.Premium }}" = 'true' ]; then
            TASKS="$TASKS assembleArm64-v8aPremiumRelease assembleArmeabi-v7aPremiumRelease assembleX86PremiumRelease assembleX86_64PremiumRelease"
          fi
          if [ "${{ github.event.inputs.Foss }}" = 'true' ]; then
            TASKS="$TASKS assembleArm64-v8aFossRelease assembleArmeabi-v7aFossRelease assembleX86FossRelease assembleX86_64FossRelease"
          fi
          if [ -z "${TASKS}" ]; then
            TASKS="assembleRelease"
          fi
          ./gradlew $TASKS --daemon --parallel

      - name: Move APKs
        run: mv ./*/build/outputs/apk/*/release/*.apk .

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: '**/*.apk'
